diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
]

private_diary/urls.py
from django.contrib import admin
from django.urls import path, include

"git clone https://tb31042g@bitbucket.org/tb31042g/private_diary.git"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    path('accounts/', include('allauth.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""

    class Meta:
        verbose_name_plural = 'CustomUser'

diary/models.py
from django.db import models

# Create your models here.

diary/forms.py
from django import forms
from django.core.mail import EmailMessage


class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'


    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = f"お問い合わせ {title}"
        message = f"送信者名：{name}\nメールアドレス：{email}\nメッセージ：\n{message}"
        from_email = 'admin@example.com'
        to_list = ['text@example.com']
        cc_list = [email]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

accounts/views.py
from django.shortcuts import render

# Create your views here.

diary/views.py
import logging

from django.contrib import messages
from django.urls import reverse_lazy
from django.views import generic
from .forms import InquiryForm

logger = logging.getLogger(__name__)


class IndexView(generic.TemplateView):
    template_name = "index.html"


class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('diary:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info(f"inquiry sent by {form.cleaned_data['name']}")
        return super().form_valid(form)

diary/templates/base.html
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'diary:index' %}">PRIVATE DIARY</a>
                <button type="button" class="navbar-toggler" data-toggle="collapse"
                        data-target="#navbarResponsive" aria-controls="navbarResponsive"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item {% block active_inquiry %}{% endblock %}">
                            <a class="nav-link" href="{% url 'diary:inquiry' %}">INQUIRY</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                            </li>
                        {% else %}
                            <li class="nav-item {% block active_signup %}{% endblock %}">
                                <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                            </li>
                            <li class="nav-item {% block active_login %}{% endblock %}">
                                <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block header %}{% endblock %}

        {% if messages %}
          <div class="container">
              <div class="row">
                  <div class="my-div-style w-100">
                      <ul class="messages" style="list-style: none;">
                          {% for message in messages %}
                          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                              {{ message }}
                          </li>
                          {% endfor %}
                      </ul>
                  </div>
              </div>
          </div>
        {% endif %}

        {% block contents %}{% endblock %}

        <!-- Footer -->
        <footer class="py-5 bg-black">
            <div class="container">
                <p class="m-0 text-center text-white small">Copyright &copy;Private Dairy 2020</p>
            </div>
            <!-- /.container -->
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    </div>
</body>
</html>

diary/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Web上にあなた専用の日記ページを保存できる
サービス | Private Diary{% endblock %}

{% block header %}
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container">
            <h1 class="masthead-heading mb-0">Private Diary</h1>
            <h2 class="masthead-subheading mb-0">あなた専用の日記保存サービス</h2>
            <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
            </a>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}
{% block contents %}
<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'img/01.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Web Diary</h2>
          <p>Web上で作成/編集/削除ができる日記</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'img/02.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">Save Your Diary</h2>
          <p>あなたの日記をWebに保存</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'img/03.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Membership System</h2>
          <p>会員制のWeb日記サービス</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

diary/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ | Private Diary{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}